### ISSUE TITLE
Does not work for python 3.5 or 2.7

### ISSUE THREAD

**Issue by ouboub** [augustin-chevallier/MathResultsGraph#2]
Hi 
I am on Ubuntu 16.04 and cannot upgrade currently.
I followed the instructions, but when running
either 
```
python TexToResultGraph.py
```
I obtain
```
File "TexToResultGraph.py", line 339
    app.exec()
           ^
```
when running 
```
/usr/bin/python3.5 exToResultGraph.py
```
I obtain
```
Traceback (most recent call last):
  File "TexToResultGraph.py", line 7, in <module>
    from PyQt6.QtCore import *
ImportError: No module named 'PyQt6'
```

I did install all required packages described in the INSTRUCTIONS and I  have pandoc installed.

```
sudo -H pip install pypandoc js2py PyQt5 packaging bs4 PyQtWebEngine

```

any idea what to do?

Uwe Brauer

**Comment by augustin-chevallier** [comment]
Hi, thanks for trying!

The doc is not up to date - it is for the last release. 

I am in the process of switching to Qt6, so you need to install pyQt6 instead of pyQt5 if you want to use the latest git version. I should update the doc.

**Comment by ouboub** [comment]
Hi 
thanks for your quick response. A couple of comments. It seems that I cannot install pyQt6 (running Ubuntu 16.04 with python 3.5 (and till summer I cannot afford to upgrade)).
So I prefer to stick with 5 if this is ok, 
I tried out the source code 0.3
but running 
```
/usr/bin/python3.5 TexToResultGraph.py
```
I obtain now:

```
Traceback (most recent call last):
  File "TexToResultGraph.py", line 10, in <module>
    import generateGraph as gg
  File "/home/oub/src/MathResultsGraph-0.3/generateGraph.py", line 7, in <module>
    from bs4 import BeautifulSoup
  File "/usr/lib/python3/dist-packages/bs4/__init__.py", line 30, in <module>
    from .builder import builder_registry, ParserRejectedMarkup
  File "/usr/lib/python3/dist-packages/bs4/builder/__init__.py", line 314, in <module>
    from . import _html5lib
  File "/usr/lib/python3/dist-packages/bs4/builder/_html5lib.py", line 70, in <module>
    class TreeBuilderForHtml5lib(html5lib.treebuilders._base.TreeBuilder):
AttributeError: module 'html5lib.treebuilders' has no attribute '_base'
```
I understand that I should use python 3.X?
I tried also 2.7:
and obtained
```
Traceback (most recent call last):
  File "TexToResultGraph.py", line 4, in <module>
    from PyQt5.QtWebEngineWidgets import *
ImportError: No module named QtWebEngineWidgets
```
so is it possible to use you package with python 3.5 (or even 2.7)?

**Comment by augustin-chevallier** [comment]
Mhh not sure about this one. First, yes this is python 3 only. Second, about the error with python3, maybe this could help: 
https://bytefreaks.net/gnulinux/attributeerror-module-html5lib-treebuilders-has-no-attribute-_base

**Comment by ouboub** [comment]
>>> "a" == augustin-chevallier  ***@***.***> writes:

> Mhh not sure about this one. First, yes this is python 3 only. Second,
> about the error with python3, maybe this could help:
> https://bytefreaks.net/gnulinux/attributeerror-module-html5lib-treebuilders-has-no-attribute-_base

Oho, that helped indeed, now I have a problem with my hm old pandoc
installation (1.19) the message I receive is that 1.19 is needed.
But a graphical interface pops up
Any change to obtain anything useful with a pandoc version this old?



-- 
Warning: Content may be disturbing to some audiences
I strongly condemn Putin's war of aggression against the Ukraine.
I support to deliver weapons to Ukraine's military. 
I support the ban of Russia from SWIFT.
I support the EU membership of the Ukraine. 
https://addons.thunderbird.net/en-US/thunderbird/addon/gmail-conversation-view/

**Comment by ouboub** [comment]
Using 
https://github.com/jgm/pandoc/releases/tag/3.1.1
I upgraded pandoc
run 
```
/usr/bin/python3.5 TexToResultGraph.py
```
the menu pops up, I select an example from your your example directory, set up the working directory, press update graph visualization, but **nothing** happens, what do I miss?

**Comment by augustin-chevallier** [comment]
Hi, 
this is strange, I cannot reproduce this bug, but my version of ubuntu is more up to date. 

However, as I mentioned in another thread about MacOs, you can probably still open the graph_save.html file with your browser (the part on the left that does nothing is just displaying this webpage. For some reason it does not work on all configurations...)

Best,
Augustin Chevallier

**Comment by ouboub** [comment]
>>> "a" == augustin-chevallier  ***@***.***> writes:

> Hi, 
> this is strange, I cannot reproduce this bug, but my version of ubuntu is more up to date. 

> However, as I mentioned in another thread about MacOs, you can
> probably still open the graph_save.html file with your browser (the
> part on the left that does nothing is just displaying this webpage.
> For some reason it does not work on all configurations...)

This file has not been generated in the MacOS!

Best

-- 
Warning: Content may be disturbing to some audiences
I strongly condemn Putin's war of aggression against the Ukraine.
I support to deliver weapons to Ukraine's military. 
I support the ban of Russia from SWIFT.
I support the EU membership of the Ukraine. 
https://addons.thunderbird.net/en-US/thunderbird/addon/gmail-conversation-view/
